package `is`.xyz.mpv

// Mapping between Android and mpv keycodes (special keys)

import android.view.KeyEvent.*

// cf. https://github.com/mpv-player/mpv/blob/master/input/keycodes.h
val keyMapping = mapOf(
    KEYCODE_SPACE to "SPACE",
    KEYCODE_ENTER to "ENTER",
    KEYCODE_TAB to "TAB",
    KEYCODE_DEL to "BS",
    KEYCODE_FORWARD_DEL to "DEL",
    KEYCODE_INSERT to "INS",
    KEYCODE_MOVE_HOME to "HOME",
    KEYCODE_MOVE_END to "END",
    KEYCODE_PAGE_UP to "PGUP",
    KEYCODE_PAGE_DOWN to "PGDWN",
    KEYCODE_ESCAPE to "ESC",
    KEYCODE_SYSRQ to "PRINT",
    KEYCODE_DPAD_RIGHT to "RIGHT",
    KEYCODE_DPAD_LEFT to "LEFT",
    KEYCODE_DPAD_DOWN to "DOWN",
    KEYCODE_DPAD_UP to "UP",
    // not bound, let the OS handle these:
    //KEYCODE_POWER to "POWER",
    //KEYCODE_MENU to "MENU",
    //KEYCODE_VOLUME_UP to "VOLUME_UP",
    //KEYCODE_VOLUME_DOWN to "VOLUME_DOWN",
    //KEYCODE_VOLUME_MUTE to "MUTE",
    //KEYCODE_HOME to "HOMEPAGE",
    //KEYCODE_SLEEP to "SLEEP",
    //KEYCODE_ENVELOPE to "MAIL",
    //KEYCODE_SEARCH to "SEARCH",
    KEYCODE_MEDIA_PLAY to "PLAYONLY",
    KEYCODE_MEDIA_PAUSE to "PAUSEONLY",
    KEYCODE_MEDIA_PLAY_PAUSE to "PLAYPAUSE",
    KEYCODE_MEDIA_STOP to "STOP",
    KEYCODE_MEDIA_FAST_FORWARD to "FORWARD",
    KEYCODE_MEDIA_REWIND to "REWIND",
    KEYCODE_MEDIA_NEXT to "NEXT",
    KEYCODE_MEDIA_PREVIOUS to "PREV",
    KEYCODE_MEDIA_RECORD to "RECORD",
    KEYCODE_CHANNEL_UP to "CHANNEL_UP",
    KEYCODE_CHANNEL_DOWN to "CHANNEL_DOWN",
    KEYCODE_ZOOM_IN to "ZOOMIN",
    KEYCODE_ZOOM_OUT to "ZOOMOUT",
    KEYCODE_F1 to "F1",
    KEYCODE_F2 to "F2",
    KEYCODE_F3 to "F3",
    KEYCODE_F4 to "F4",
    KEYCODE_F5 to "F5",
    KEYCODE_F6 to "F6",
    KEYCODE_F7 to "F7",
    KEYCODE_F8 to "F8",
    KEYCODE_F9 to "F9",
    KEYCODE_F10 to "F10",
    KEYCODE_F11 to "F11",
    KEYCODE_F12 to "F12",
    KEYCODE_NUMPAD_0 to "KP0",
    KEYCODE_NUMPAD_1 to "KP1",
    KEYCODE_NUMPAD_2 to "KP2",
    KEYCODE_NUMPAD_3 to "KP3",
    KEYCODE_NUMPAD_4 to "KP4",
    KEYCODE_NUMPAD_5 to "KP5",
    KEYCODE_NUMPAD_6 to "KP6",
    KEYCODE_NUMPAD_7 to "KP7",
    KEYCODE_NUMPAD_8 to "KP8",
    KEYCODE_NUMPAD_9 to "KP9",
    KEYCODE_NUMPAD_DOT to "KP_DEC",
    KEYCODE_NUMPAD_ENTER to "KP_ENTER",
    // Special mapping of programmable colour keys
    KEYCODE_PROG_RED to "F13",
    KEYCODE_PROG_GREEN to "F14",
    KEYCODE_PROG_YELLOW to "F15",
    KEYCODE_PROG_BLUE to "F16",
)
