name: Build APK

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Export environment variables
        run: buildscripts/include/ci.sh export >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: gh-cache/
          key: mpv-android-cache-${{ hashFiles('buildscripts/**') }}

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf pkgconf libtool ninja-build python3-pip gperf
          # This special command downloads the newest version of Meson
          sudo pip3 install --break-system-packages meson

      - name: Download or build dependencies
        run: |
          mkdir -p "$CACHE_FOLDER"
          buildscripts/include/ci.sh install
        env:
          CACHE_MODE: folder
          CACHE_FOLDER: ${{ github.workspace }}/gh-cache

      - name: Build APK
        run: buildscripts/include/ci.sh build

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: mpv-android-apk
          path: app/build/outputs/apk/**/*.apk
